# =========================================================
# Oil & Gas AI Analytics Platform
# FULL SAFE VERSION – NO KEYERRORS
# =========================================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from statsmodels.tsa.arima.model import ARIMA
from pptx import Presentation
import io

# =========================================================
# PAGE CONFIG
# =========================================================
st.set_page_config(
    page_title="Oil & Gas AI Analytics",
    page_icon="🛢️",
    layout="wide"
)

# =========================================================
# ALLOWED SHEETS (USER REQUIREMENT)
# =========================================================
ALLOWED_SHEETS = [
    "Report",
    "Remarks",
    "Well data",
    "Water Flooding",
    "Pico test",
    "Lab BS&W",
    "Test data",
    "Code list",
    "Fluid shots",
    "Tank Status",
    "Trucks & Tanks calculation",
    "NRA & Suez Shipping",
    "Yesterday data",
    "PRODUCTION DPR Report",
    "Station situation"
]

# =========================================================
# ROLE BASED ACCESS
# =========================================================
ROLES = {
    "Viewer": ["Dashboard"],
    "Engineer": ["Dashboard", "ML & Forecast"],
    "Admin": ["Dashboard", "ML & Forecast", "Admin"]
}

def login():
    st.sidebar.title("🔐 Login")
    username = st.sidebar.text_input("Username")
    role = st.sidebar.selectbox("Role", list(ROLES.keys()))
    return username, role

# =========================================================
# LOAD ONLY ALLOWED SHEETS
# =========================================================
@st.cache_data
def load_allowed_sheets(file):
    xls = pd.ExcelFile(file)
    sheets = {}
    for sheet in xls.sheet_names:
        if sheet in ALLOWED_SHEETS:
            sheets[sheet] = pd.read_excel(xls, sheet_name=sheet)
    return sheets

# =========================================================
# VALIDATE REQUIRED COLUMNS
# =========================================================
def validate_required_columns(df, required_cols):
    return [c for c in required_cols if c not in df.columns]

# =========================================================
# WELL HEALTH SCORE (0–100)
# =========================================================
def health_score(net_bo, net_diff, wc):
    score = 100

    if net_bo <= 0:
        score -= 40
    elif net_bo < 100:
        score -= 20

    if net_diff < 0:
        score -= min(abs(net_diff) / 10, 30)

    if wc is not None:
        if wc > 80:
            score -= 30
        elif wc > 60:
            score -= 15

    return max(0, round(score))

# =========================================================
# ARIMA FORECAST
# =========================================================
def forecast_series(series):
    try:
        model = ARIMA(series, order=(1, 1, 1))
        fit = model.fit()
        return fit.forecast(steps=5)
    except:
        return None

# =========================================================
# ML CLUSTERING
# =========================================================
def cluster_wells(df):
    features = df[['Net BO', 'Net Diff BO']].fillna(0)
    kmeans = KMeans(n_clusters=3, random_state=42)
    df['Cluster'] = kmeans.fit_predict(features)
    return df

# =========================================================
# POWERPOINT GENERATOR
# =========================================================
def create_ppt(stats, df):
    prs = Presentation()

    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = "Production Analytics Report"
    slide.placeholders[1].text = "Auto-generated by AI Analytics Platform"

    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Executive Summary"
    slide.placeholders[1].text_frame.text = (
        f"Total Wells: {stats['wells']}\n"
        f"Average Health Score: {stats['health']}\n"
        f"Zero Production Wells: {stats['zero']}"
    )

    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "High Risk Wells"
    risky = df[df['Health Score'] < 50]['Well'].astype(str).head(10)
    slide.placeholders[1].text_frame.text = ", ".join(risky)

    buffer = io.BytesIO()
    prs.save(buffer)
    buffer.seek(0)
    return buffer

# =========================================================
# MAIN APPLICATION
# =========================================================
def main():
    user, role = login()

    st.title("🛢️ Oil & Gas AI Analytics Platform")
    st.caption("Safe multi-sheet analytics • No crashes • Field-ready")

    uploaded_file = st.file_uploader(
        "📤 Upload Production Excel File",
        type=["xlsx", "xlsm"]
    )

    if not uploaded_file:
        st.info("Please upload a production Excel file.")
        return

    sheets = load_allowed_sheets(uploaded_file)

    if not sheets:
        st.error("❌ None of the required sheets were found in this file.")
        st.stop()

    # -----------------------------------------------------
    # SHEET SELECTION
    # -----------------------------------------------------
    st.sidebar.subheader("📄 Available Sheets")
    selected_sheet = st.sidebar.selectbox(
        "Select Production Sheet",
        list(sheets.keys())
    )

    df = sheets[selected_sheet]

    if df.empty:
        st.warning("⚠️ Selected sheet is empty.")
        st.stop()

    # -----------------------------------------------------
    # COLUMN MAPPING
    # -----------------------------------------------------
    with st.sidebar:
        st.subheader("🧩 Column Mapping")

        field_col = st.selectbox("Field Column", df.columns)
        well_col = st.selectbox("Well Column", df.columns)
        net_bo_col = st.selectbox("Net BO Column", df.columns)
        net_diff_col = st.selectbox("Net Diff BO Column", df.columns)
        wc_col = st.selectbox("W/C Column (optional)", ["None"] + list(df.columns))
        wc_col = None if wc_col == "None" else wc_col

    df = df.rename(columns={
        field_col: "Field",
        well_col: "Well",
        net_bo_col: "Net BO",
        net_diff_col: "Net Diff BO"
    })

    if wc_col:
        df = df.rename(columns={wc_col: "WC"})

    # -----------------------------------------------------
    # VALIDATION (THIS FIXES KEYERROR)
    # -----------------------------------------------------
    required_cols = ["Net BO", "Net Diff BO"]
    if wc_col:
        required_cols.append("WC")

    missing_cols = validate_required_columns(df, required_cols)

    if missing_cols:
        st.error(
            f"❌ Selected sheet is missing required columns: {', '.join(missing_cols)}"
        )
        st.info("💡 Please select the correct PRODUCTION sheet.")
        st.stop()

    # -----------------------------------------------------
    # HEALTH SCORE
    # -----------------------------------------------------
    df['Health Score'] = df.apply(
        lambda r: health_score(
            r["Net BO"],
            r["Net Diff BO"],
            r["WC"] if "WC" in df.columns else None
        ),
        axis=1
    )

    # =====================================================
    # DASHBOARD
    # =====================================================
    if "Dashboard" in ROLES[role]:
        st.header("📊 Production Dashboard")

        c1, c2, c3 = st.columns(3)
        c1.metric("Total Wells", len(df))
        c2.metric("Average Health Score", round(df["Health Score"].mean(), 1))
        c3.metric("Zero Production Wells", (df["Net BO"] == 0).sum())

        st.dataframe(df.sort_values("Health Score"))

        st.subheader("📈 Pareto Analysis (80/20)")
        d = df.sort_values("Net BO", ascending=False)
        d["CumPct"] = d["Net BO"].cumsum() / d["Net BO"].sum()
        fig, ax = plt.subplots()
        ax.plot(d["CumPct"], marker="o")
        ax.axhline(0.8, color="red", linestyle="--")
        st.pyplot(fig)

    # =====================================================
    # ML & FORECAST
    # =====================================================
    if "ML & Forecast" in ROLES[role]:
        st.header("🧠 ML & Forecasting")

        df = cluster_wells(df)
        st.dataframe(df[["Well", "Cluster", "Health Score"]])

        st.subheader("🔮 Production Forecast")
        selected_well = st.selectbox("Select Well", df["Well"].unique())
        series = df[df["Well"] == selected_well]["Net BO"]
        forecast = forecast_series(series)

        if forecast is not None:
            st.line_chart(pd.concat([series, forecast]))

    # =====================================================
    # ADMIN – POWERPOINT
    # =====================================================
    if "Admin" in ROLES[role]:
        st.header("📊 Auto PowerPoint Report")

        stats = {
            "wells": len(df),
            "health": round(df["Health Score"].mean(), 1),
            "zero": (df["Net BO"] == 0).sum()
        }

        ppt = create_ppt(stats, df)

        st.download_button(
            "📥 Download PowerPoint",
            ppt,
            "production_report.pptx",
            mime="application/vnd.openxmlformats-officedocument.presentationml.presentation"
        )

    st.success("✅ Analysis Completed Successfully")

# =========================================================
if __name__ == "__main__":
    main()
